# Generated by Django 5.1.6 on 2025-04-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_password_reset",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_code",
            field=models.CharField(default="", max_length=6),
        ),
    ]
