# Generated by Django 5.1.6 on 2025-04-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_is_password_reset_user_verification_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_password_reset",
        ),
        migrations.RemoveField(
            model_name="user",
            name="verification_code",
        ),
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Токен"
            ),
        ),
    ]
