# Generated by Django 5.1.6 on 2025-04-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.CharField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="Slug"
            ),
        ),
    ]
