# Generated by Django 5.1.6 on 2025-03-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(default=None, verbose_name="Дата создания"),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                default=None, verbose_name="Дата последнего изменения"
            ),
        ),
    ]
