# Generated by Django 5.1.6 on 2025-04-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="version_number",
            field=models.IntegerField(default=1, verbose_name="Номер версии"),
        ),
    ]
